version: '3.8'

services:
  frontend:
    image: fronts
    container_name: angular
    ports:
      - "4200:80"

  backend:
    image: b2
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/employeemanager?allowPublicKeyRetrieval=true

      #      MYSQL_HOST: mysqlcontainer
#      MYSQL_PORT: 3306
#      MYSQL_DB_NAME: employeemanager
#      MYSQL_USER: root
#      MYSQL_PASSWORD:
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: employeemanager
#      MYSQL_USER: root
#      MYSQL_PASSWORD:

#networks:
#  default:
#    name: networkmysql
#    external: true



