version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "ihm"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    container_name: spring
    depends_on:
      - mysql
    build: ./
    image: back
    ports:
      - 8089:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ihm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect

  frontend:
    container_name: angular
    build: ./
    image: front
    ports:
      - "4200:80"
volumes:
  db_data: